### Get request example
GET http://localhost:8080/main
Accept: text/html

###

POST http://localhost:8080/login 
Accept: text/html

###

GET http://localhost:8080/somePage
Accept: text/html

###

GET http://localhost:8080/refresh
Accept: text/html

###

POST http://localhost:8080/logout 
Accept: text/html